### ISSUE TITLE
Link multiple pictures to a day

### ISSUE THREAD

**Issue by nvllz** [Demizo/Daily_You#17]
Hi, I find this application very interesting. I wonder how you would like Daily You to be used. I can see that it's inspired by OneShot, but I personally see much more potential in making it more of a memory-like app, instead of just a single overall picture of a day. I mean a way to link multiple pictures to a day, which would be useful for capturing memories. Let's say you had a cool day at an interesting place where you took some cool pictures that are so good you can't pick just one. I think it's a must-have if you consider the app to be a daily memory keeper.

**Comment by Demizo** [comment]
Good Idea! I want to add this. I was originally going to have everything you add to a day be modular, for example multiple images, text boxes, or moods. For simplicity I trimmed it down. I do want to bring back the ability to have multiple images per day, so you can expect to see this feature.

**Comment by maverick74** [comment]
My two cents on this:

be careful to not destroy the app's magic! The one-photo limitation is what makes it special!

I'm not saying "don't implement it!" just implement it carefully!!!

Maybe multiple pictures support could be an option - off by default!

Or maybe you could link multiple pictures but have to pick which would be "the one" (the one would be the picture shown everywhere while once you tap it, you would enter _that day_ and be able to see the other ones...)

**Comment by Demizo** [comment]
I have been giving this some thought. 

I think a good approach would be to take after how Instagram shows a small icon on posts with more than one image. This way the cards for each day will still only show the first image. For actually seeing multiple images in logs, it could be a horizontal scroll list.

I think this would have next to no impact on the way the app would currently be used while also making more than one image an option.

**Comment by maverick74** [comment]
Yeah, I think that would be a nice approach! It will probably work 🙂

**Comment by maverick74** [comment]
I was thinking of this also... there should be a way to choose which picture is the first (or the one we want to represent that day)

**Comment by Rafee-M** [comment]
> I think a good approach would be to take after how Instagram shows a small icon on posts with more than one image. This way the cards for each day will still only show the first image. For actually seeing multiple images in logs, it could be a horizontal scroll list.

Totally agree with this. What do you think about making this a bit more customizable, by adding an option to show a small collage/stack of images as the thumbnail
