### ISSUE TITLE
Show entries from x years ago on the main screen

### ISSUE THREAD

**Issue by nvllz** [Demizo/Daily_You#19]
I just added entries and set them to be exactly two and three years ago, and was expecting them to show up in the main screen list, but all I can see is a "one year ago" entry. I think it would be great to have a nice Snapchat Memories-like experience with yearly reminders for specific days. So if something happened exactly two, four, or seven years ago, you'd be reminded of it on the home screen.

**Comment by Demizo** [comment]
Hahaha. Yeah right now the home page is an after thought. There are very few "flashbacks" and the year one is just 365 days, not actually a true year. This should definitely be built out to offer more interesting insights.

**Comment by Demizo** [comment]
As a side note it couldn't have been fun to go back that many years by swiping. You'll enjoy the jump to date feature in the next release 😄
