### ISSUE TITLE
Support SAF Document Providers 

### ISSUE THREAD

**Issue by antrmn** [Demizo/Daily_You#28]
Selecting Nextcloud or Anemo as the Image/Log folder currently has no effect. It would be nice to have full support for SAF document providers since it would give the app much more versatility: it would allow the app to seamless integrate with a cloud or encryption solution.

**Comment by Demizo** [comment]
I know :( One of the original motivations for making this app was to use the nextcloud SAF. I will need to look more into this to see if it is possible because the external storage permission clearly is not enough.

**Comment by antrmn** [comment]
Thanks for the quick response and for acknowledging such a powerful feature that currently few apps seem to support. Unfortunately I don't know the technicalities behind it so I don't know how hard it could be to implement.

**Comment by Demizo** [comment]
I will leave this open until I figure out if it is feasible or not 🤞

Right now I just have the image folder autoupload to nextcloud using the nextcloud app. I made a custom autoupload folder for the db as well since by default the nextcloud autouploader only detects media folders.

**Comment by Demizo** [comment]
As an update it appears the backup service in Aegis Authenticator is able to write directly to the nextcloud SAF and it is auto uploaded to the nextcloud server. There may be limitations in Flutter preventing this, but it may be possible after all.

**Comment by antrmn** [comment]
> As an update it appears the backup service in Aegis Authenticator is able to write directly to the nextcloud SAF and it is auto uploaded to the nextcloud server. 

Thank you for pointing this out. As a reference, I wrote a list of apps which support NextCloud here: https://github.com/you-apps/RecordYou/issues/190#issuecomment-1703958035 I hope it can be helpful by any sort.

**Comment by Demizo** [comment]
@antrmn Thank you for the references! I definitely want to get this working!
