### ISSUE TITLE
Weekstart setting

### ISSUE THREAD

**Issue by blaugrau3001** [Demizo/Daily_You#32]
It would be a cool feature, probably not so hard to change the of a week, right now the week on the calendarpage starts with sunday, but in most european countrys the week starts with monday. This setting probably adds some more confience.
Very cool app, good job as right now

**Comment by Demizo** [comment]
Whoops didn't cross my mind! I am pretty sure that wouldn't be hard to add as at least a setting even if it doesn't auto detect local.

Thanks for pointing this out
