### ISSUE TITLE
Taking pictures from within app using phones camera

### ISSUE THREAD

**Issue by Darius499** [Demizo/Daily_You#35]
Hello,
Started using this app today and I really like it. I have two suggestions, could it be added that after clicking Log Today to use phones camera to take picture instead of opening gallery and choosing already taken picture(there is camera icon but when I click it nothing happens,only when I click gallery icon it shows pictures from gallery).

Also could it be added that instead of previous day,a week ago or something similar it shows pictures description (for example today I took photo of basketball and wrote basketball in description, could it be added that below picture it shows basketball and not previous)?

Hope you understand what I am trying to say and suggest.
Also again really like the app even after using it only one day and thank you for making the app.

**Comment by Demizo** [comment]
uh oh! A shortcut to the camera would be a nice addition, but the camera button not working is a bug. Could your provide details about what android version/OS you are using as well as what camera app you have installed?

As for the home page I think I get what you are saying. I am planning an overhaul of the home screen, I want to include larger cards that also have the entry text, but as of right now there are some technical issues with that.

**Comment by Darius499** [comment]
I am using Android 13 crDroid 9.8 Custom Rom and using Google Camera Gcam_RN8P_Mod by Wyroczen, phone is Redmi Note 8 Pro.

**Comment by Darius499** [comment]
![Screenshot_20230816-024616_Daily You_1.png](https://github.com/Demizo/Daily_You/assets/87473278/e2d31ffc-54f2-4519-9d18-902dd345082f)

Here is screenshot, when I click on camera icon nothing happens.

**Comment by Demizo** [comment]
Thank you! It should launch the system camera within the app, clearly it is not. I can't think of a great way to debug this off the top of my head, I will think it over. 

Right now my best guess is it can't find the system camera activity. If I can't find a fix for your configuration, I may be able to add an option as a fallback in settings to just launch the phone camera app. You would still need to bring the image in manually, but at least you would have a camera shortcut.

**Comment by Darius499** [comment]
I disabled system camera app, just know I enabled it and by clicking on camera icon it launches stock camera. Sorry for bothering,didn't think of just enabling camera app that came preinstalled.
Thank you again and looking foward to improvements.

**Comment by Demizo** [comment]
No bother at all, I'm just glad it works!
