### ISSUE TITLE
More Toolbars to customize text when writing

### ISSUE THREAD

**Issue by nyanikoding** [Demizo/Daily_You#39]
Tools like:
- Bold
- Italic
- Underlined
- Highlight
- Font-Size
- ect.

When adding a text notes. Just like Word

**Comment by Demizo** [comment]
I will point out that most of that is possible already since it supports markdown. I will leave this open since a shortcut toolbar that automatically formats selected text with markdown via the options you mentioned could improve usability.

**Comment by Kasi07** [comment]
In Threema there is the possibillity to select a word and long press on it. Besides the options like copy and cut there are also options for Bold, Italic, etc. Maybe that would be a way to go about it without cluttering the UI too much.

**Comment by Demizo** [comment]
Oooo good idea!

**Comment by jspivey40** [comment]
A small toolbar for the markdown would be great. It could be a toggle option to turn it on and off for those that do not want it, and could auto-hide when not in use or if scrolling up and down in document.

I personally can remember most markdown code but being able to select a word and tap markdown option on toolbar and have word enclosed in the markdown code you tapped is a very friendly option. Also I don't know about others, but I appreciate a good toolbar that I can show/hide as I please. It makes the app more easily adoptable by less experienced users as no need to memorize commands and shows right in a screenshot a good bit of the editor capability for potential users. It's a win win with the option being a toggle on/off in settings or a menu. Awesome app BTW!

**Comment by Rafee-M** [comment]
> In Threema there is the possibillity to select a word and long press on it. Besides the options like copy and cut there are also options for Bold, Italic, etc. Maybe that would be a way to go about it without cluttering the UI too much.


Similar to how [Doable](https://codeberg.org/florian-obernberger/flutter-doable) handles it as well I assume
![InCollage_20240106_131436164](https://github.com/Demizo/Daily_You/assets/69535896/1804a490-079f-44c9-be13-15f7efd4ad20)
