### ISSUE TITLE
long-pressing the arrows will teleport you a year farther or earlier

### ISSUE THREAD

**Issue by Wjxfi** [Demizo/Daily_You#4]
![this](https://files.catbox.moe/9o86y6.jpg)

**Comment by Demizo** [comment]
Could you elaborate slightly on the behavior you are experiencing? Pressing the arrows should only move by one month upon release of the button. Is it jumping as you hold or does it jump a ton after you release holding?

**Comment by Demizo** [comment]
Oh I see, my bad! Yeah in testing I found going back years to be tedious. I should add a option to jump to a year or date.
