### ISSUE TITLE
Daily reminders stop after phone reboot

### ISSUE THREAD

**Issue by Zoarial94** [Demizo/Daily_You#51]
Every time my phone reboots (updates or otherwise), I have to open the app again to start receiving notifications. On multiple occasions, this has caused me to miss multiple days before I remember the app exists. 

Is there some way to have to background reminder notification service start on boot?

I am running a Pixel 6 Pro on Graphene OS. This issue is present on Android 13 and 14.

**Comment by Demizo** [comment]
Good catch! Taking a cursory glance I don't seem to subscribe to any device startup event for re-establishing notifications. I will need to look into what android best practices are for this behavior, but my hope is it will be a simple fix.

**Comment by Zoarial94** [comment]
Haha!! Seems like the fix was simple enough. Thanks!
