### ISSUE TITLE
Can't access files on system

### ISSUE THREAD

**Issue by Ranger-NF** [Demizo/Daily_You#65]
**Issues:** 
- Can't add images to logs (Tried camera and uploading - Camera takes photo but doesn't add the image to it)
- Can't change where the files are stored (It gives me the dialog box but fails to apply the changes)

**Device info:** Android 8 

**App Version:** 1.7.0 (Downloaded using droid-ify)

**Comment by Demizo** [comment]
@Ranger-NF Did the app prompt for file/storage permissions and was the permission granted?

Also what are your image/log folders (the folder paths are listed on the settings page)

**Comment by Ranger-NF** [comment]
@Demizo I have double checked the permission. It has been granted

Log folder stays the same even when I set the folder. Here are the screenshots:
- Before:
![settings_when_reset](https://github.com/Demizo/Daily_You/assets/78952725/aca5b94d-13a0-43dd-a2da-2827c68278d2)
- After (see how image folder gets changed):
![settings_when_changed](https://github.com/Demizo/Daily_You/assets/78952725/0213c1e7-4fed-4928-880f-21e3b638eacd)

**Comment by Demizo** [comment]
@Ranger-NF I ran the app in an android 8 emulator and ran into similar issues. I can use the app normally and add photos if the image and log paths are defaulted to the app's internal folders. However, like you I can not change the log or image folders to anything meaningful. This is do to a lack of read/write permissions on android 8. The storage permissions I am requesting aren't enough for old android versions. I am exploring how to best add these permissions without effecting later android versions.

**Comment by Ranger-NF** [comment]
Ok, unfortunately the issue is not completely fixed. I can change the path to all directories **except** `Documents` and its sub-directories.

ie, When I try to change the path `/0/Documents` or `/0/Documents/Diary/` the app behaves as mentioned above (path doesn't change for log folder and it changes to `/` for images)

Its not a big issue for me rn. I'm okay with creating a new folder in `/0/` (It seems to work). I will update if there are any other such weird bugs

**Comment by Demizo** [comment]
@Ranger-NF I will double check if this is true of the documents folder, but I know some directories are protected on android from apps just reading/writing to them without a specific api. Additionally flutter has some limitations when it comes to platform specific apis like android. I may need to implement the file access logic in native android code at some point. I should also have an error message when a folder can't be accessed to make the behavior less confusing.

**Comment by Demizo** [comment]
@Ranger-NF Let me know if the move to SAF in the latest update fixes this!

**Comment by Ranger-NF** [comment]
@Demizo It seems to have been fixed on the new version. Good job mate!
