### ISSUE TITLE
Camera confirm oob

### ISSUE THREAD

**Issue by Martinligabue** [Demizo/Daily_You#70]
I'm not sure if it's a problem with the system camera or this app, but the confirm button is under the virtual back/home/all apps buttons, I can click it, but it's not visible, like it's in a semi-fullscreen, so it's expecting that that space is usable, while instead it's drawn over by the system buttons.
It's the only app that does this, that's why I'm asking here.

![photo_2024-01-07_18-15-55](https://github.com/Demizo/Daily_You/assets/22115672/93f0aefd-abe0-4fdf-8c8b-52858d394066)

**Comment by Demizo** [comment]
What confirm button are you referring to? The button to confirm the picture you just took? What version of android are you on and what camera app are you using? Daily You should just launch your system's camera app. Also are the buttons or nav bar in Daily You covered up by the system navigation buttons?

**Comment by Martinligabue** [comment]
I'm on Android 13

The default camera is org.lineageos.aperture

The other buttons are fine

While checking for the other apps I noticed that they don't use the default camera app but each of them has an internal one, so I'll go notify on the other repo, as I understand it's not a bug in this app

**Comment by Demizo** [comment]
Feel free to reopen this issue if you suspect this app again!
