### ISSUE TITLE
Can't install app from IzzyOnDroid

### ISSUE THREAD

**Issue by Ranger-NF** [Demizo/Daily_You#89]
I use Droid-ify to install apps, and while installing v2.0.0 of the app (from IzzyOnDroid repo), it shows **Could not validate Daily You** 

![Droidify error](https://i.imgur.com/bn0eXhA.jpg)

For versions prior to v2.0.0, it was installing just fine. I guess it has something to do with signing of the app?

**Comment by Demizo** [comment]
@Ranger-NF Yes, the app is now signed as of 2.0.0. You will need to uninstall the previous im order to update.

**Comment by Demizo** [comment]
@Ranger-NF Yes, the app is now signed as of 2.0.0. You will need to uninstall the previous im order to update.

**Comment by Ranger-NF** [comment]
I had uninstalled the older app before trying to install it though. hmm...

**Comment by Demizo** [comment]
i would try an adb unistall to be sure the old version is gone

**Comment by Ranger-NF** [comment]
I can't see any package name related to this app... I will wait for next version and see if this problem persist 👍

**Comment by Demizo** [comment]
Hmm, have you installed the app on your device with adb while developing? I sometimes had to uninstall with adb to allow a fresh install. Alternatively, I would try the apk directly from github or restarting your phone after uninstalling th old app.

**Comment by Ranger-NF** [comment]
@Demizo I just restarted my phone, that didn't fix it.

But I don't think the problem has to do anything with my phone or the older version. Droid-ify refuses to even download it. ie, When I press `install`, it shows the error. I suspect it must be a problem related to either Droid-ify or IzzyOnDroid. 

But I can be wrong as no other individual has reported such case. Side Note: I download apk file from Github and it works fine. So, its all good I guess 🤷

**Comment by Demizo** [comment]
Odd. I am using neostore and am able to download the app from the issy repo. If you cant update from the issy repo after the next update reopen this issue.

**Comment by Ranger-NF** [comment]
Atlast, I fixed. Sorry to have bothered you. I found out that Droid-ify doesn't sync the repos on its own... I synced it and woilah! I can now install v2.0.1!

Btw, Thank you for your quick responses. Hope you a wonderful rest of your day/night!
